version: '3.2'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
    env_file:
      - .env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - web:web

  data:
    image: postgres:latest
    volumes:
      - data-volume:/var/lib/postgresql
    command: "true"

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - data-volume:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  data-volume: